spring:
  application:
    name: MoonName
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/moonname}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:migration

jwt:
  secret: ${JWT_SECRET:moonname-super-secret-key-2026-assez-longue-pour-hmac}
  access-validity: 900
  refresh-validity: 604800

server:
  port: 8080
